# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setMinimumSize(QtCore.QSize(720, 405))
        MainWindow.setSizeIncrement(QtCore.QSize(720, 405))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setContentsMargins(9, 0, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(80, 28))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(100, 80))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_search)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_list = QtWidgets.QWidget(self.tab_search)
        self.widget_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_list.setObjectName("widget_list")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_list)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listWidget_play = QtWidgets.QListWidget(self.widget_list)
        self.listWidget_play.setObjectName("listWidget_play")
        self.gridLayout_3.addWidget(self.listWidget_play, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_list, 1, 0, 1, 1)
        self.widget_label = QtWidgets.QWidget(self.tab_search)
        self.widget_label.setMinimumSize(QtCore.QSize(200, 30))
        self.widget_label.setMaximumSize(QtCore.QSize(200, 30))
        self.widget_label.setObjectName("widget_label")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_label)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_label)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout_2.addWidget(self.widget_label, 0, 0, 1, 1)
        self.gridLayout_play = QtWidgets.QGridLayout()
        self.gridLayout_play.setObjectName("gridLayout_play")
        self.gridLayout_2.addLayout(self.gridLayout_play, 0, 1, 3, 1)
        self.pushButton_stop_all = QtWidgets.QPushButton(self.tab_search)
        self.pushButton_stop_all.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_stop_all.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_stop_all.setObjectName("pushButton_stop_all")
        self.gridLayout_2.addWidget(self.pushButton_stop_all, 2, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/imgs/检测_副本.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_search, icon, "")
        self.tab_people = QtWidgets.QWidget()
        self.tab_people.setObjectName("tab_people")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_people)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget = QtWidgets.QWidget(self.tab_people)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_3.setMouseTracking(False)
        self.widget_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_3.setAutoFillBackground(False)
        self.widget_3.setObjectName("widget_3")
        self.formLayout = QtWidgets.QFormLayout(self.widget_3)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_people_search = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_people_search.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_people_search.setMaximumSize(QtCore.QSize(80, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/11720/.designer/backup/data/imgs/search_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_people_search.setIcon(icon1)
        self.pushButton_people_search.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_people_search.setObjectName("pushButton_people_search")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_people_search)
        self.lineEdit_people = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_people.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_people.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_people.setObjectName("lineEdit_people")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_people)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_2.setObjectName("widget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton_people_add = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_people_add.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_people_add.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_people_add.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/11720/.designer/backup/data/imgs/add_people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_people_add.setIcon(icon2)
        self.pushButton_people_add.setObjectName("pushButton_people_add")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_people_add)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.gridLayout_11.addWidget(self.widget, 0, 0, 1, 1)
        self.tableWidget_people = QtWidgets.QTableWidget(self.tab_people)
        self.tableWidget_people.setObjectName("tableWidget_people")
        self.tableWidget_people.setColumnCount(0)
        self.tableWidget_people.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidget_people, 1, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/imgs/人员管理_副本.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_people, icon3, "")
        self.tab_video = QtWidgets.QWidget()
        self.tab_video.setObjectName("tab_video")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_video)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_video = QtWidgets.QTableWidget(self.tab_video)
        self.tableWidget_video.setObjectName("tableWidget_video")
        self.tableWidget_video.setColumnCount(0)
        self.tableWidget_video.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_video, 2, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.tab_video)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget_5)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.pushButton_video_search = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_video_search.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_video_search.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_video_search.setIcon(icon1)
        self.pushButton_video_search.setObjectName("pushButton_video_search")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_video_search)
        self.lineEdit_video = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_video.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_video.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_video)
        self.horizontalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_video_deselect = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_video_deselect.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_video_deselect.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_video_deselect.setObjectName("pushButton_video_deselect")
        self.gridLayout_5.addWidget(self.pushButton_video_deselect, 0, 1, 1, 1)
        self.pushButton_video_check = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_video_check.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_video_check.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_video_check.setObjectName("pushButton_video_check")
        self.gridLayout_5.addWidget(self.pushButton_video_check, 0, 2, 1, 1)
        self.pushButton_video_add = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_video_add.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_video_add.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_video_add.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/11720/.designer/backup/data/imgs/add_video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_video_add.setIcon(icon4)
        self.pushButton_video_add.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_video_add.setObjectName("pushButton_video_add")
        self.gridLayout_5.addWidget(self.pushButton_video_add, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_6, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addWidget(self.widget_4, 1, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("data/imgs/符号-视频_副本.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_video, icon5, "")
        self.tab_tv = QtWidgets.QWidget()
        self.tab_tv.setObjectName("tab_tv")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_tv)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_7 = QtWidgets.QWidget(self.tab_tv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_8.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget_8.setObjectName("widget_8")
        self.formLayout_5 = QtWidgets.QFormLayout(self.widget_8)
        self.formLayout_5.setContentsMargins(0, 0, -1, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.lineEdit_tv = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_tv.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_tv.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_tv.setObjectName("lineEdit_tv")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_tv)
        self.pushButton_tv_search = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_tv_search.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_tv_search.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_tv_search.setIcon(icon1)
        self.pushButton_tv_search.setObjectName("pushButton_tv_search")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_tv_search)
        self.horizontalLayout_4.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_tv_add = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_tv_add.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_tv_add.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_tv_add.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_tv_add.setIcon(icon4)
        self.pushButton_tv_add.setObjectName("pushButton_tv_add")
        self.horizontalLayout_3.addWidget(self.pushButton_tv_add)
        self.pushButton_tv_deselect = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_tv_deselect.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_tv_deselect.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_tv_deselect.setObjectName("pushButton_tv_deselect")
        self.horizontalLayout_3.addWidget(self.pushButton_tv_deselect)
        self.pushButton_tv_check = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_tv_check.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_tv_check.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_tv_check.setObjectName("pushButton_tv_check")
        self.horizontalLayout_3.addWidget(self.pushButton_tv_check)
        self.horizontalLayout_4.addWidget(self.widget_9, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_4.addWidget(self.widget_7, 0, 0, 1, 1)
        self.tableWidget_tv = QtWidgets.QTableWidget(self.tab_tv)
        self.tableWidget_tv.setObjectName("tableWidget_tv")
        self.tableWidget_tv.setColumnCount(0)
        self.tableWidget_tv.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget_tv, 1, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("data/imgs/电视_副本.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_tv, icon6, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_8.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 75))
        self.widget_11.setMaximumSize(QtCore.QSize(100, 75))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_5.addWidget(self.widget_11)
        self.widget_top1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_top1.setMinimumSize(QtCore.QSize(0, 75))
        self.widget_top1.setMaximumSize(QtCore.QSize(16777215, 75))
        self.widget_top1.setObjectName("widget_top1")
        self.horizontalLayout_5.addWidget(self.widget_top1)
        self.widget_top2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_top2.setMinimumSize(QtCore.QSize(450, 75))
        self.widget_top2.setMaximumSize(QtCore.QSize(200, 75))
        self.widget_top2.setObjectName("widget_top2")
        self.horizontalLayout_5.addWidget(self.widget_top2)
        self.widget_top3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_top3.setMinimumSize(QtCore.QSize(0, 75))
        self.widget_top3.setMaximumSize(QtCore.QSize(16777215, 75))
        self.widget_top3.setObjectName("widget_top3")
        self.horizontalLayout_5.addWidget(self.widget_top3)
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 75))
        self.widget_10.setMaximumSize(QtCore.QSize(100, 75))
        self.widget_10.setObjectName("widget_10")
        self.pushButton_min = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_min.setGeometry(QtCore.QRect(15, 5, 25, 25))
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_max = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_max.setGeometry(QtCore.QRect(45, 5, 25, 25))
        self.pushButton_max.setText("")
        self.pushButton_max.setObjectName("pushButton_max")
        self.pushButton_close = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_close.setGeometry(QtCore.QRect(75, 5, 25, 25))
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_5.addWidget(self.widget_10)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "   视频列表"))
        self.pushButton_stop_all.setText(_translate("MainWindow", "结束全部检测"))
        self.pushButton_people_search.setText(_translate("MainWindow", "  搜索  "))
        self.pushButton_people_add.setText(_translate("MainWindow", "  添加  "))
        self.pushButton_video_search.setText(_translate("MainWindow", "  搜索  "))
        self.pushButton_video_deselect.setText(_translate("MainWindow", "取消选择"))
        self.pushButton_video_check.setText(_translate("MainWindow", "检测"))
        self.pushButton_video_add.setText(_translate("MainWindow", "  添加  "))
        self.pushButton_tv_search.setText(_translate("MainWindow", "  搜索  "))
        self.pushButton_tv_add.setText(_translate("MainWindow", "  添加  "))
        self.pushButton_tv_deselect.setText(_translate("MainWindow", "取消选择"))
        self.pushButton_tv_check.setText(_translate("MainWindow", "检测"))

